# Generated by Django 4.0.4 on 2022-05-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('auther', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
